[workspace]
resolver = "3"
members = [
    "doro",
    "doro-macro",
    "doro-util",
    "doro-test",
    "benches"
]

[patch.crates-io]
bendy = { path = "lib/bendy" }

# 性能调试用
[profile.release]
debug = 1 # 启用调试信息
strip = false # 不要去除 symbols
