[package]
name = "dorodoro-bangumi"
version = "0.1.0"
edition = "2024"

[dependencies]
#tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
byteorder = "1.4"
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
bytes = "1.10.1"
sha1 = "0.10.6"
hashlink = "0.10.0"
percent-encoding = "2.3.1"
