[package]
name = "doro-macro"
version = "0.1.0"
autotests = false
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit-mut", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"